version: 2.1
orbs:
  node: circleci/node@4.8.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout # check out the code in the project directory
            - run: echo "hello world" # run the `echo` command
            # - run: npm install
            # - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test